### ISSUE TITLE
Use git-lfs to store packages.min.json

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#104]
packages.min.json it's already too huge, and it's minified, so there is no need to use git itself to manage it, should move on git-lfs, and maybe we can even turn on build with SRI in it in the mean time.

> $ git push
> Counting objects: 6, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (6/6), done.
> Writing objects: 100% (6/6), 25.04 MiB | 2.97 MiB/s, done.
> Total 6 (delta 4), reused 0 (delta 0)
> remote: error: GH001: Large files detected.
> remote: error: Trace: 7dc2082b8c4103cad477100d620117a6
> remote: error: See http://git.io/iEPt8g for more information.
> remote: error: File public/packages.min.json is 132.66 MB; this exceeds GitHub's file size limit of 100.00 MB
> To git@github.com:cdnjs/new-website.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@github.com:cdnjs/new-website.git'

**Comment by xtuc** [comment]
packages.min.json is now stored in Google storage
