### ISSUE TITLE
How to run it use local database?

### ISSUE THREAD

**Issue by liangzai-cool** [cdnjs/new-website#108]
How to run this project use local mongodb? I can't find where to use `MONGOHQ_URL` in this project.

thank you!

**Comment by Shadowmad** [comment]
Same question. +1

**Comment by PeterDaveHello** [comment]
@liangzai-cool hmmmm ... actually it was deprecated, cc @thomasdavis

**Comment by PeterDaveHello** [comment]
@Shadowmad You can run the server without that db.

**Comment by liangzai-cool** [comment]
thank you!
you mean `http://cdnjs.com/` website is running without mongodb just use `public/packages.min.json` instead db now ?

thank you!

**Comment by PeterDaveHello** [comment]
@liangzai-cool Yes it is.

**Comment by liangzai-cool** [comment]
oh~ It's much to my surprise! can you tell me, does `autoupdate` maintain `public/packages.min.json` file ? 
If it's right, i'll to learn the `autoupdate` how to maintain the `public/package.min.json`.
I want to learn how does the whole website  `cdnjs.com` to work.

Thank you!

**Comment by PeterDaveHello** [comment]
Nope, `./build/packages.json.js` maintains `public/packages.min.json`.

See https://github.com/cdnjs/buildScript/blob/master/update-website.sh#L146-L161
```bash
        msg="Rebuild meta data phase 1"
        output Info "$msg" gitter
        run node build/packages.json.js

        msg="Rebuild meta data phase 2"
        output Info "$msg" gitter
        run cd $basePath/$webRepo
        run node update.js

        msg="Commit meta data update in website repo"
        output Info "$msg" gitter
        for file in atom.xml packages.min.json rss.xml sitemap.xml
        do
            run git add public/$file
        done
        run git commit --message="meta data"
```
