### ISSUE TITLE
inline mode doesn't work without selection

### ISSUE THREAD

**Issue by soisme** [cdnjs/new-website#110]
See the demo doesn't work:
https://www.froala.com/wysiwyg-editor/docs/examples/inline
But it will work when you add toolbarVisibleWithoutSelection: true like https://www.froala.com/wysiwyg-editor/docs/examples/always-visible

I am on Chrome.

**Comment by soisme** [comment]
BTW I am on Chrome.

**Comment by PeterDaveHello** [comment]
You should ask its author, not CDNJS.

**Comment by soisme** [comment]
oh sorry i am on the wrong github page.
