### ISSUE TITLE
Transfer to use mongodb

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#119]
Load whole the `packages.min.json` to memory will make the heroku app crash(https://github.com/cdnjs/cdnjs/issues/7623#issuecomment-212145577), it's time to transfer to use something like mongodb.

 `packages.min.json` can still be there so that we still have a file containing all the artifacts, and also we don't need to change the procedure to generate the artifacts, so there may be two things to do here:
1. Load `packages.min.json` to mongodb
2. Let webServer.js and apiServer.js read data from db instead of the origin json file.

**Comment by thomasdavis** [comment]
@PeterDaveHello Can you add my personal email as a collaborator. I will fix this tonight and fix the redux  page too.

**Comment by PeterDaveHello** [comment]
@thomasdavis you mean where? Heroku?

**Comment by thomasdavis** [comment]
Got access to it, all good.

**Comment by PeterDaveHello** [comment]
@thomasdavis do me a favor, let's create another free heroku dyno and another git branch for this feature first, we need to make sure everything stable than update the build script.

**Comment by thomasdavis** [comment]
@PeterDaveHello I've started working on a new branch called `rewrite`

- I will set it up to use mongo/redis/memcache, not sure yet.
- It will use es6 (node 6.2.0)
- Because the packages will be external we can move towards separating the api and webserver
- will make it more modular and just cleaner code
- we will change over to use pm2 for app instances, don't see why we won't be able to run 5 app instances

**Comment by PeterDaveHello** [comment]
@thomasdavis are the features you are going to use compatible with nodejs v4? Actually I have some problems with nodejs v6 like the broken build of cdnjs or something, so that's the reason why we still stay on nodejs v4 until now.

**Comment by thomasdavis** [comment]
It won't be, thus we will have to segment the server code quite a bit. It can live in this branch for a while until then.

**Comment by PeterDaveHello** [comment]
Ignore this one.
