### ISSUE TITLE
GitHub repos assumed in Javascript

### ISSUE THREAD

**Issue by DataTables** [cdnjs/new-website#122]
[It looks like it is assumed that a repo will be hosted on github](https://github.com/cdnjs/new-website/blob/c49294be3dd6a611728fe9de00dbcc17cbbab25a/public/js/main.js#L127). This of course is not always the case and a number of search results are resulting in errors:

main.js:10 Uncaught TypeError: Cannot read property 'repo' of undefined

For example load: https://cdnjs.com/#q=pdf .

**Comment by PeterDaveHello** [comment]
@DataTables Thanks for report, I will take a look at it.

**Comment by PeterDaveHello** [comment]
@DataTables this is because we currently only support GitHub, I don't this that's a problem.

**Comment by DataTables** [comment]
The thing is that this issue breaks the site. For example, if you load up the main page and type `p` you'll see the results for that letter - then type `d` to search for `pd` and there is a Javascript error so its impossible to view results for `pd` (and also `pdf`). Basically any package that you list which doesn't have a `github` object (which appears to be quite a few of them) causes the search results not to display.

Just a few lines after the one I linked to there is:

```
if (hit.github) {
```

Is it not possible to just add that to the `if` condition I linked to?

**Comment by PeterDaveHello** [comment]
Oops, sorry that I didn't notice that, should fix it!

**Comment by DataTables** [comment]
Looks like it was only just introduced a few days ago with c0c0125d7b6529e9ca02225e4504045fadca3384.

**Comment by PeterDaveHello** [comment]
@DataTables fixed, thank you very much for your report, the update has deployed, would you please purge your local cache and give it a try? Thanks.

**Comment by DataTables** [comment]
Absolutely awesome - thanks.

And thank you for maintaining this awesome resource. cdnjs is just such a wonderful tool to be able to have for web devs.

**Comment by PeterDaveHello** [comment]
@DataTables no probs
