### ISSUE TITLE
Keep scrolling normally after sections?

### ISSUE THREAD

**Issue by vk011** [cdnjs/new-website#124]
Hello,

The plugin works great, but after all the sections I have a footer, would it be possible to scroll to that footer normally after the last section?

**Comment by PeterDaveHello** [comment]
Hi @vk011,
Sorry for the late reply, I didn't really got your problem, can you explain in detail? Thanks.

**Comment by vk011** [comment]
I am sorry I somehow posted this in the wrong place.
