### ISSUE TITLE
Show some animation when waiting for searching result loading

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#126]
To improve user experience.

**Comment by PeterDaveHello** [comment]
* 3f1a95a set appLoading animate color Peter Dave Hello 2 minutes ago 
* 8657745 adj appLoading js codes Peter Dave Hello 2 minutes ago 
* fac9a6a use on(input) instead on(keyup change) for searchHandler Peter Dave Hello 3 minutes ago 
* b98c012 add search progress animate via "app-loading" Peter Dave Hello 50 minutes ago 
* 51a7bc3 include "app-loading" library Peter Dave Hello 50 minutes ago

**Comment by thomasdavis** [comment]
nice
