### ISSUE TITLE
cdn URLs are relative on some library pages, absolute on some others

### ISSUE THREAD

**Issue by peey** [cdnjs/new-website#134]
For example, the page at https://cdnjs.com/libraries/normalize
shows links in the format `https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.css`

And the page at https://cdnjs.com/libraries/lodash.js/
shows links in the format `lodash.js/4.13.1/lodash.js`

I would suggest using the full/absolute url everywhere. Or at least that the prefix 'https://cdnjs.cloudflare.com/ajax/libs/' be mentioned somewhere on the page if it has to be relative urls.

Because it's really hard to find the prefix `https://cdnjs.cloudflare.com/ajax/libs/`, also it is a source of confusion as people may try to use the relative url on the domain they're currently browsing on, i.e. `https://cdnjs.com/libraries/`

**Comment by PeterDaveHello** [comment]
@peey I think they are totally the same, the pages you have no prefix may be caused by the not executed js functions, would you please try to refresh?  Thanks.

**Comment by peey** [comment]
It was likely a caching issue. I still saw this bug until I used the "browse library" function and it somehow got fixed.
