### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed

### ISSUE THREAD

**Issue by sabrinaluo** [cdnjs/new-website#135]
Hi, I'm using 
`chrome Version 51.0.2704.106 (64-bit)`
`3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Can't see the copy button anymore, and there is an error in the console. 

What should I do to get the lib url? thank you.

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' *.carbonads.com *.getclicky.com fonts.gstatic.com www.google-analytics.com fonts.googleapis.com cdnjs.cloudflare.com 'unsafe-inline' https: data: ".
```

![selection_106](https://cloud.githubusercontent.com/assets/5300359/16909638/7c1b5762-4d06-11e6-9fc3-4d9fc01ef453.png)

**Comment by PeterDaveHello** [comment]
@sabrinaluo would you please try it again? Actually I don't this error message you provided really have something to do with this problem, the error is a known issue just didn't been solved yet, would you please try it again? Or just use `Ctrl` + `F5` to force refresh this page? Thanks.

**Comment by sabrinaluo** [comment]
Hi, I can see the `copy` button now, and it's good to use. 
But I still see the error message in the console. So the error might not be relevant to the button issue.
![selection_109](https://cloud.githubusercontent.com/assets/5300359/17045339/28cea59e-4ffb-11e6-95dc-fcdd54e43384.png)
It shows the full URL of each lib now, so even if the button doesn't show or work, I still can get the URL. 

This issue can be closed. Great work! Thank you! :tada:

**Comment by PeterDaveHello** [comment]
Yes, the error it's about the js codes inserted from CloudFlare CDN, should have nothing to do with your problem.
