### ISSUE TITLE
Add library's npm package and downloads count per month info

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#146]
Just like the GitHub repository and popularity info :)

Part 1: Algolia search
Part 2: library package

GitHub repo link and popularity info example:

![image](https://cloud.githubusercontent.com/assets/3691490/20524392/57779ea4-b0f5-11e6-85f0-e0f3adbef802.png)

**Comment by dakshshah96** [comment]
We can use the following to get download info from npm:

(**Using d3 as an example, replace d3 with package name**)

* Last day: https://api.npmjs.org/downloads/point/last-day/d3
* Last week: https://api.npmjs.org/downloads/point/last-week/d3
* Last month: https://api.npmjs.org/downloads/point/last-month/d3

**Comment by PeterDaveHello** [comment]
Decide not to implement this, GitHub popularity could be good enough.
