### ISSUE TITLE
SRI support on search result

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#152]
We only support SRI info on the library page right now, should work on the search result soon.

**Comment by MattIPv4** [comment]
To get this working it looks like algolia search needs to return the SRI value for the default file for each lib in the hits data. I'm not quite sure where algolia is fetching the data from so I am very unsure as to how to implement this on the backend to get it working.

@PeterDaveHello any help or guidance as to where Algolia gets the data from would be great :)
