### ISSUE TITLE
Bad font rendering on library template

### ISSUE THREAD

**Issue by PaoloFalomo** [cdnjs/new-website#153]
Hi there! 

## The problem
Currently the number of views,stars and forks of a library is inside the `<i>` html compromising the font-rendering of the number:
![image](https://cloud.githubusercontent.com/assets/10535089/22685202/b7a25c5e-ed1f-11e6-8bc8-f3fddb3e8b55.png)

## Proposed solution
Edit the unordered list inside the library [template](https://github.com/cdnjs/new-website/blob/master/templates/library.html#L11) moving the `<strong>` tag outside the `<i>` tag.

```diff
<ul class="list-inline">
-   <li><i class="fa fa-eye"><strong> {{watch}}</strong></i></li>
+   <li><i class="fa fa-eye"></i><strong> {{watch}}</strong></li>
-   <li><i class="fa fa-star"><strong> {{star}}</strong></i></li>
+   <li><i class="fa fa-star"></i><strong> {{star}}</strong></li>
-   <li><i class="fa fa-code-fork"><strong> {{fork}}</strong></i></li>
+   <li><i class="fa fa-code-fork"></i><strong> {{fork}}</strong></li>
</ul>
```

After that it should be fine 👍 
_example_
![image](https://cloud.githubusercontent.com/assets/10535089/22685431/8ff63210-ed20-11e6-96ab-da2a09eacf8a.png)

**Comment by PeterDaveHello** [comment]
@PaoloFalomo thanks for your report, would you like to send a pull request? Thanks!

**Comment by PaoloFalomo** [comment]
Yep, but i am not able to do that. Can u help me?

**Comment by PeterDaveHello** [comment]
@PaoloFalomo Not your if you are familiar with pull request?
https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

**Comment by PaoloFalomo** [comment]
thank u @PeterDaveHello ,

but i get this error when trying to publish my branch:
![image](https://cloud.githubusercontent.com/assets/10535089/23029826/0eb16136-f46c-11e6-85c2-59830d2be1be.png)

**Comment by PeterDaveHello** [comment]
@PaoloFalomo what is the environment and what are the steps to here? Maybe you'll try a easier way - to directly edit the file and fire a pull request online? 

There is a edit button here: https://github.com/cdnjs/new-website/blob/master/templates/library.html

**Comment by PaoloFalomo** [comment]
oh yea @PeterDaveHello !! That's great i've just lost my pullrequest verginity. 😸
