### ISSUE TITLE
Improve library browse page

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#155]
It's not that good to list all the libraries at once: https://cdnjs.com/libraries

Ideas:
 1. Add a simple filter like we use on https://cdnjs.com.tw/ demo (provided by caddy server), note that filter is not search or fuzzy search.
![image](https://cloud.githubusercontent.com/assets/3691490/23095846/13db9690-f64c-11e6-9b8c-4c3ac44af3f6.png)
![image](https://cloud.githubusercontent.com/assets/3691490/23095850/2d327d52-f64c-11e6-8d2f-a408583b6ccb.png)
2. Add options to browse by the first character, from 0-9 and a-z
3. Infinite scroll
4. There should still be a button to extend the page to show all the libraries at once

Hope this will be good enough.

**Comment by qas612820704** [comment]
Hi @PeterDaveHello, can you detail about 1?
I don't know the difference between the origin one and the goal.

**Comment by PeterDaveHello** [comment]
@qas612820704 of course, I wanted to add a simple "filter" in the libraries page, it'll not like to fuzzy search feature like the homepage one, but I'm not sure if this is really good or something we really need yet, just an opening discussion here, thanks!

**Comment by qas612820704** [comment]
Hi @PeterDaveHello , I'm sorry response so late.

The https://cdnjs.com/libraries has two different views.
1. One is generated by server.
![screenshot from 2017-05-10 17-27-30](https://cloud.githubusercontent.com/assets/8502252/25892241/5388a726-35a6-11e7-8076-8d7c25f9b19f.png)
2. The other is the search results of algolia
![screenshot from 2017-05-10 17-27-53](https://cloud.githubusercontent.com/assets/8502252/25892242/54e9f912-35a6-11e7-88dd-a97b2156b838.png)

So, which data should we use to improve brower page?

from the
1. `server(public/packages.json)`, writing search method by ourself
or
2. `algolia`, restrict search results to exact match?

> Or this two data is actually the same? I'm not sure that

**Comment by PeterDaveHello** [comment]
It should use the page generated by the server directly, however I wonder if this feature would make users confused and maybe we should focus on other features with more value I think, thanks for discussion here.
