### ISSUE TITLE
Add missing "Last-Modified" and "ETag" headers

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#157]
We don't have these two headers for the pages

Some ref:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
http://dev.mobify.com/blog/beginners-guide-to-http-cache-headers/

**Comment by PeterDaveHello** [comment]
@pvnr0082t wanna take a look? Not hard at all at code level but you'll learn something about web performance and cache control.

**Comment by drewfreyling** [comment]
We'd also have to make sure that conditional `GET` requests work with the right 200 or 304 as well. I'm happy to take a look @PeterDaveHello ?

**Comment by PeterDaveHello** [comment]
@drewfreyling Please, thanks!

**Comment by drewfreyling** [comment]
@PeterDaveHello going to use the last modified date of the template for this. Seem reasonable?

**Comment by PeterDaveHello** [comment]
hmmm, maybe not, I think many parts depend on the `packages.min.json`?

**Comment by drewfreyling** [comment]
So what means the page has changed? A complex check of the template, 'packages.min.json' and other things? This could get hard. Front and about pages should just be template though?

**Comment by PeterDaveHello** [comment]
@drewfreyling Yes this is hard, the content means if it's changed or not, the template is one reason, the packages.min.json is also one.
The about page, 404, could depends on template I agree, not sure if you mean the homepage "front"?

**Comment by drewfreyling** [comment]
#199 closes this
