### ISSUE TITLE
Display library assets group by types

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#158]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42392527)](https://www.bountysource.com/issues/42392527-display-library-assets-group-by-types?utm_source=42392527&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Groups examples:
- js
- css
- image
- font
- other

**Comment by gmalz** [comment]
Hello, I would like to know more about your problem? 
For example, on what language? At what level ?

**Comment by PeterDaveHello** [comment]
@gmalz I think all the library names would be in English and numbers 😄

**Comment by bhargav175** [comment]
@PeterDaveHello Want to fix this, can you elaborate the issue a little more?

**Comment by PeterDaveHello** [comment]
@bhargav175 sure thing, currently we list the assets all in the same block, please take codemirror as exmaple, what we want to do is to group the different file types in the different blocks, the special part here is to put the map file with its origin file, may be css or js file.
