### ISSUE TITLE
Move to use algoliasearch lite version?

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#167]
Just take a look at different algolia v3.21.1 releases:
```
algoliasearch.jquery.min.js 59K
algoliasearchLite.min.js 37K
algoliasearch.min.js 58K
```

I wonder if we can use algoliasearchLite instead, 56% size diff, could make the website lighter, should compare the different parts and trace the related codes and then we'll know if we can move to the lite version.

**Comment by PeterDaveHello** [comment]
Hi @redox ! It's been a while since our last conversation, would you be interested in take a look at this one? (Since I think you're the one most familiar with it 😄 ) Thanks!

**Comment by redox** [comment]
> Hi @redox ! It's been a while since our last conversation, would you be interested in take a look at this one? (Since I think you're the one most familiar with it 😄 ) Thanks!

Oh wow, sure 👍

**Comment by PeterDaveHello** [comment]
Thanks @redox
