### ISSUE TITLE
Copy buttons not working on unsecure connection

### ISSUE THREAD

**Issue by Maroniemann** [cdnjs/new-website#17]
The dropdown works, but all copy buttons (Copy, Copy HTTP and Copy HTTPS) look (highlighting and changed cursor) like a clickable button just for one tick. Trying to click does nothing. The one-tick-highlight also happens only once unless I highlighted another button in the meantime.

On secure connections (HTTPS) the buttons work properly

**Comment by PeterDaveHello** [comment]
@Maroniemann do you still have this problem? Thanks.

**Comment by Maroniemann** [comment]
Well, I'm not using Chromium or Debian anymore, but I just tried it with Firefox and Chrome on Windows 8.1 N and it is working.

**Comment by PeterDaveHello** [comment]
Okay, I have no problem with Chromium v43.0.2357.130 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)

@Piicksarn Would you like to help us reproduce this problem on on Debian Jessie 64bit with Chromium?

**Comment by Piicksarn** [comment]
@PeterDaveHello I checkout the problem on two environments. 

1. First one is `Safari` and the result is fine.

2. The second is `Firefox v39.0 on Ubuntu 14.04`, and it comes some problems about the button's function:
  - It occur the same problem with @Maroniemann 

  - It didn't show the copy buttons in library content, and the result shown below:

![2015-08-07 14 19 33](https://cloud.githubusercontent.com/assets/8291251/9129862/66fee914-3d0f-11e5-9da4-99b23ad70e6c.png)

Is it possible to make an `help wanted` issue to make users to report their environment and the result?

**Comment by PeterDaveHello** [comment]
@Piicksarn any msg from console?

**Comment by PeterDaveHello** [comment]
button changed by #97 #100, @Maroniemann can you check if you still have the problem?

**Comment by Maroniemann** [comment]
I tested with Firefox 41.0.2 and Chrome 46.0.2490.80 on Gentoo, both without Flash, and both are working.

**Comment by PeterDaveHello** [comment]
So I think we can close this now?

**Comment by Maroniemann** [comment]
I think so
