### ISSUE TITLE
Restructing webServer.js. ex: separate routes to a route dir

### ISSUE THREAD

**Issue by qas612820704** [cdnjs/new-website#175]
Eg:
```js
//  webServer.js:445
  app.get('/libraries/:library/:version', ...);

  app.get('/libraries/:library', ...);

  app.get('/libraries', function(req, res) {
    ...
  });

  ...

```

It can separate into

```js
  // webServer.js:445
  ...
  var libRouter = require('router/libraries');
  app.use('/libraries', libRouter);
  ...
```
and
```js
  // router/libraries.js
  var router = require('express').Router()
  router.get('/:library/:version', ...);
  router.get('/:library', ...);
  router.get('/libraries', ...);
  module.exports = router;
```

It can let codes more concise.

I have interest about restructing this app, and standardize the coding style by lint #174.

Is there any **suggestion** and **principle** to follow?

**Comment by MattIPv4** [comment]
@qas612820704 I really like this as an idea, webServer.js is currently rather messy and this would really help with refactoring it all and splitting it up into more manageable sections. If you wish to do this, I say go for it!
