### ISSUE TITLE
add link to github repo

### ISSUE THREAD

**Issue by ahmetb** [cdnjs/new-website#180]
There are no links to this github repo/org from most cdnjs.com page, there's only link to PeterDaveHello's github profile.

I had to click "Contact us", only then I found out I must report issues on GitHub.

**Comment by PeterDaveHello** [comment]
There is link of https://github.com/cdnjs/cdnjs on the corner, should be good enough for most users, as it's the main cdnjs repo, and also contains website repo info in the readme, also we don't really mind that you created issues at cdnjs/cdnjs (Though creating issue at cdnjs/new-website is of course better 👍 ), thanks for suggestion anyway.
