### ISSUE TITLE
[Bug] [Website] Too large Algolia logo on mobile.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#189]
Though we don't really support mobile devices yet (the layout it's just for desktop as 99.9% web developers won't use their phone to write webpage), the size of Algolia logo is pretty too large.

Screenshot:
![default](https://user-images.githubusercontent.com/3691490/27772705-24355b7c-5f9a-11e7-9f1d-2831c0840c69.png)

I believe that this appears after #173, which turned to use svg image on logo which is scalable.

**Comment by Haroenv** [comment]
That's right, it only happens on mobile user agents, is there a mobile/desktop version of the page?

**Comment by PeterDaveHello** [comment]
@Haroenv We have only one version, so it's decided by user-agent? Didn't notice that!

**Comment by Haroenv** [comment]
I don't understand it either, but if you spoof the user agent, you can see the difference between mobile and desktop, even on the same screen size 

<img width="440" alt="screen shot 2017-07-03 at 09 23 20" src="https://user-images.githubusercontent.com/6270048/27782083-442c48d2-5fd1-11e7-827d-c4b1ea2660e2.png">
<img width="467" alt="screen shot 2017-07-03 at 09 23 10" src="https://user-images.githubusercontent.com/6270048/27782085-444bede0-5fd1-11e7-88ea-536637f9029c.png">

**Comment by PeterDaveHello** [comment]
Wow, that's interesting! There may be a secret inside that svg image that we don't know 🤔

**Comment by Haroenv** [comment]
I have a feeling that different css is sent depending on the UA, but didn't dig deep enough. It's definitely not in the svg itself, I wrote that

**Comment by PeterDaveHello** [comment]
hmmm ... we use same `main.css` and `theme.css`, I'll test the website locally to see if there is any difference in case of there is any config on CDN touched the files, but looks like we don't have the same problem before switching to svg logo.

**Comment by dakshshah96** [comment]
This is definitely happening because of a user-agent dependant rule. I tested it out and noticed the following:

* The Algolia logo is displayed correctly because of the `width` and `height` set in the `style` attribute (home.html):

```
<img src="/img/algolia.svg" style="height: 20px; width:75;" />
```

* The `style` attribute is absent on mobile user agents due to which the SVG file is displayed in its full size (probably a `width: 100%` rule somewhere):

```
<img src="/img/algolia.svg" />
```

**Comment by PeterDaveHello** [comment]
Looks like it's only on cdnjs.com, not locally, I'll dig our configs on Cloudfalre.

**Comment by PeterDaveHello** [comment]
I think I found the bug:

![image](https://user-images.githubusercontent.com/3691490/27807251-3cded314-6072-11e7-9d8a-d1aba92e78f8.png)

Mirage is now disabled on Cloudflare panel, thanks guys, @Haroenv @dakshshah96 😄

**Comment by Haroenv** [comment]
🤔 interesting

**Comment by PeterDaveHello** [comment]
@Haroenv totally

**Comment by PeterDaveHello** [comment]
We are good now!

![default](https://user-images.githubusercontent.com/3691490/27807390-09bdcb88-6073-11e7-932f-595c317c039a.png)

**Comment by dakshshah96** [comment]
@PeterDaveHello Awesome.. beta after all 😄
