### ISSUE TITLE
Add Sitelinks Searchbox

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/new-website#202]
Google Search can expose a search box scoped to your website when it appears as a search result.
And I think this would be a good function of this website.

Maybe we can add the followings code into `templates/layout.html`
```js
<script type="application/ld+json">
{
  "@context":"https://schema.org",
  "@type": "WebSite",
  "url": "https://cdnjs.com/",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://cdnjs.com/libraries/{search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
</script>
```
(Using the tool: https://search.google.com/structured-data/testing-tool)

What do you think?

Thanks.

Ref: https://developers.google.com/search/docs/data-types/sitelinks-searchbox

**Comment by PeterDaveHello** [comment]
@sufuf3 awesome 👍
