### ISSUE TITLE
Missing package-lock.json file

### ISSUE THREAD

**Issue by jmgaya** [cdnjs/new-website#257]
While following the *README.md*, a _package-lock.json_ file is created, if the user installs the dependencies through _npm_. Shall we add this file to repository?

**Comment by MattIPv4** [comment]
@PeterDaveHello Do you know of a reason why this isn't yet committed?

**Comment by PeterDaveHello** [comment]
I don't think we really need to add it. Maybe we'll just ignore it in the `.gitignore` Thanks.

**Comment by MattIPv4** [comment]
@PeterDaveHello Whilst on the topic of gitignore, is there a reason the SRI folder is included in git? It drives me insane having to unselect it at every commit?

**Comment by PeterDaveHello** [comment]
@MattIPv4 you can use sparseCheckout to ignore it.

**Comment by MattIPv4** [comment]
@PeterDaveHello I plan to create a PR to resolve this soon. I will add `package-lock.json` to the `.gitignore` file. Should I also add `SRI/` to it as this is an automatically generated folder, or do you want it tracked still?

**Comment by PeterDaveHello** [comment]
@MattIPv4 any reason to exclude SRI/? BTW, they should be separated issue.

**Comment by MattIPv4** [comment]
@PeterDaveHello I don't see why it needs to be tracked, isn't it automatically generated when the site is deployed?

**Comment by PeterDaveHello** [comment]
@MattIPv4 it's automatically generated when the site is built, but why not?

**Comment by MattIPv4** [comment]
@PeterDaveHello It's just another thing to have to consider when setting up sparseCheckout, or when making a commit.

For someone new who wants to contribute, they may think they need to commit the updated contents of `SRI`, which then slows down the PR process as it has to be cleaned up?

**Comment by PeterDaveHello** [comment]
@MattIPv4 I prefer to publish the SRI data to be tracable publicly so anyone has suspicion or wants to prove the integrity and easily audit them.

I'll be happy to help anyone facing issue with contribution if the situation happend, so far I didn't see related issues yet 🙂

**Comment by MattIPv4** [comment]
@PeterDaveHello Ah, that makes sense. Thank you :)
I'll make the PR to remove package-lock shortly.

**Comment by PeterDaveHello** [comment]
@MattIPv4 Thank you.
