### ISSUE TITLE
throw new Error('Start function required') at throng.js line 22

### ISSUE THREAD

**Issue by ZtianWisc** [cdnjs/new-website#264]
Question: trying to run webServer.js. I am running node v10.13.0 and OSX. Thanks for your help!

**Comment by MattIPv4** [comment]
Hi there, this is due to the fact that the code is currently written to work with an older version of throng. #256 fixes this by updating the minimum version of throng and re-ordering the start arguments.

**Comment by ZtianWisc** [comment]
I checked my package.json, it does use
`"throng": "^4.0.0"`
but still get same error
`node_modules/throng/lib/throng.js:22    
throw new Error('Start function required');
`

**Comment by ZtianWisc** [comment]
@MattIPv4 got it thanks!
