### ISSUE TITLE
Make library names and descriptions a single button

### ISSUE THREAD

**Issue by Stryxus** [cdnjs/new-website#277]
I find it a bit tedious when i need to click on the libraries name specifically, especially on libraries with short names.

Why not make the name and description a button for easier selection?

**Comment by mpark86** [comment]
Hi, can I try working on this?

**Comment by MattIPv4** [comment]
@mpark86 Absolutely, go for it!
I believe the relevant code will be https://github.com/cdnjs/new-website/blob/master/public/js/main.js#L237-L277

**Comment by mpark86** [comment]
Thank you! I'll take a look
