### ISSUE TITLE
Make SRI default

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/new-website#279]
Following the [recent article from Troy Hunt](https://www.troyhunt.com/the-javascript-supply-chain-paradox-sri-csp-and-trust-in-third-party-libraries/) and the [feedback of users](https://twitter.com/PatrickSocha/status/1127885966092447744) [on Twitter](https://twitter.com/forensicmike1/status/1127905681317646336), I think it would be best for us to ensure that SRI options are the default.

I feel the best way to implement this would be to make the "Copy" button default to "Copy Link/Script Tag with SRI" for all JS/CSS assets.

Additionally, if a user uses the "Copy Link/Script Tag" button that doesn't make use of SRI, show a modal explaining the benefits of using SRI.

**Comment by PeterDaveHello** [comment]
@MattIPv4 before that, I prefer to increase the sha level, and on the other side, the modal would be to aggressive to me.

**Comment by MattIPv4** [comment]
@PeterDaveHello I'll leave the change in sha level to you :)

With the modal, I think it could be something that could use a cookie or similar so that it only needs to show once, simply educating users who may not be aware of the benefits to security of using SRO.

However, if we make the SRI copy default and "fade" the non-sri copy options, this may on its own encourage more users to use SRI.

**Comment by drewfreyling** [comment]
https://github.com/cdnjs/cdnjs/issues/13384 tracks the changing of the SHA level
