### ISSUE TITLE
[website 404 not found]

### ISSUE THREAD

**Issue by EmexProf** [cdnjs/new-website#294]
http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css

The above page (content) was referenced in my webpage as containing mixed content (without https). 

Kindly assist to me to locate it in my site folder so as to resolve the mixed content issues raised.

Thanks.
![Ajax mixed content](https://emeximages.githubusercontent.com/38656208/61265926-7ca4a080-a78a-11e9-9fb4-3cb8159b7d4b.PNG)

**Comment by MattIPv4** [comment]
@EmexProf The resource is loading fine over https - Do you have a live example of the issue you are having?

**Comment by MattIPv4** [comment]
No progress, closing.
