### ISSUE TITLE
public/css/*.css needs to be linted

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/new-website#299]
We are adding linting for all main files relating to the website. We have already implemented eslint for the backend scripts and linting for the HTML templates and front-end JS are in the works.

We should also be linting the main css files that are used for the site to ensure they also keep a good code style standard going forward.

**Comment by drewfreyling** [comment]
What are you thinking? Stylelint?

**Comment by MattIPv4** [comment]
Hey @drewfreyling, yup, I think I plan to go for stylelint over csslint.
Do you have any preference on what base rules we use, or should I just build up a config based around what we have already?

**Comment by drewfreyling** [comment]
@MattIPv4 I normally just use `stylelint-config-standard` rules
