### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by aliglelo** [cdnjs/new-website#305]
Please add a dark mode to website so it is not heavy on our eyes during work at night hours

**Comment by MattIPv4** [comment]
The new website design will have this: https://github.com/cdnjs/brand/tree/master/website

**Comment by aliglelo** [comment]
Thanks for your response
best of luck
By the Way when new design is coming?

**Comment by MattIPv4** [comment]
Not really sure when it will happen - I want to get it built but need to get everything in the pre-redesign milestone (https://github.com/cdnjs/new-website/milestone/1) completed first, but I lack merge access (see https://github.com/cdnjs/cdnjs/issues/13524)

**Comment by aliglelo** [comment]
Well best of luck...
