### ISSUE TITLE
Add Algolia into Sponsors

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#31]
Hey @redox,

Would you like to add Algolia into sponsors?
Currently, sponsors are listed here : https://cdnjs.com/about, maybe you'll like to send a PR to add it :)

**Comment by redox** [comment]
Oh I would love to :) I'll try to submit a PR later this week end. Thank you!

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Looks good, close this now.
