### ISSUE TITLE
Hide file types that are not distributed by the cdn

### ISSUE THREAD

**Issue by xtuc** [cdnjs/new-website#321]
We filter out files given a list of extension that can be distrubted by the cdn.

Example that don't work https://cdnjs.cloudflare.com/ajax/libs/antd/4.0.0-rc.1/antd.dark.less https://cdnjs.cloudflare.com/ajax/libs/antd/4.0.0-rc.1/report.html,  that can you find on https://cdnjs.com/libraries/antd/4.0.0-rc.1.

**Comment by MattIPv4** [comment]
@xtuc Can you find the full list of extensions the cdn permits? I've never actually seen the full list.

**Comment by xtuc** [comment]
The list is `js, css, png, gif, jpg, jpeg, swf, svg, ttf, eot, woff, woff2, otf, map, cur, mp3, ogg, aac, scss, webp, json` with `wasm, hpb` being extension that we will add.
