### ISSUE TITLE
Japanese in ja.cdnjs.com is incorrect

### ISSUE THREAD

**Issue by e-jigsaw** [cdnjs/new-website#34]
I found a Japanese translated cdnjs. It is good to Japanese speaker!

However, I think Japanese word is incorrect. So I want to fix it.

I searched translation file in this repository, but I can not found. How to contribute this?

Thanks

**Comment by PeterDaveHello** [comment]
Sorry that we are using Google translate, so we can not manually fix the wording.

**Comment by e-jigsaw** [comment]
It is very unfortunate...

Do you have any plan to foreign languages? (ex: i18n)

**Comment by PeterDaveHello** [comment]
Should ask @thomasdavis, ha.

**Comment by e-jigsaw** [comment]
thanks @PeterDaveHello , waiting for @thomasdavis .

**Comment by thomasdavis** [comment]
We've had so many requests for different languages to be manual now that I should probably implement it. Maybe we should setup a translations yaml file...

**Comment by e-jigsaw** [comment]
That is in favor. I know setup is hard, but I will try.

**Comment by thomasdavis** [comment]
Alright, are you familiar with yaml?

**Comment by e-jigsaw** [comment]
Yes, I written yaml in `travis.yml`, `circle.yml` and Rails project.

**Comment by PeterDaveHello** [comment]
Maybe we can use Transifex fo help manage translations.

**Comment by e-jigsaw** [comment]
@thomasdavis sorry I am late. Please review :arrow_up: PR

**Comment by PeterDaveHello** [comment]
@e-jigsaw sorry that we are too busy so didn't review it yet, this PR can't not be merged now, would you please rebase your branch with our latest master branch to make sure it can be merged, then I'll review it, sorry for the inconvenience.

**Comment by e-jigsaw** [comment]
@PeterDaveHello ok

**Comment by e-jigsaw** [comment]
@PeterDaveHello I was fixed locations had been changed so far. Please review again, Thanks.

**Comment by PeterDaveHello** [comment]
Okay, I'll do it within a week.

**Comment by PeterDaveHello** [comment]
Close due to no response on #35, sorry.
