### ISSUE TITLE
Uptime page not work!

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#36]
http://stats.pingdom.com/htbkuegtgycv is broken for a while, @thomasdavis would you please take a look at it? thanks.

**Comment by thomasdavis** [comment]
What conclusion did you come to @ryankirkman ?

**Comment by ryankirkman** [comment]
Fixed: https://github.com/cdnjs/new-website/commit/b42afad542d73709155570a57c728c85785317d9

**Comment by PeterDaveHello** [comment]
thanks.
