### ISSUE TITLE
Need double click on search result

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#37]
I think we don't have to click twice before using algolia search, but not sure.

**Comment by vigneshshanmugam** [comment]
Happening on any particular browser?. Couldn't reproduce this issue.

**Comment by PeterDaveHello** [comment]
At least on my Firefox (35.0.1+build1-0ubuntu0.14.04.1) Chromium (40.0.2214.111-0ubuntu0.14.04.1.1069) Google Chrome (40.0.2214.115-1) on my LinuxMint, but also get this problem on other environments.
This problem will only appear after 'search', without search, I have no problem.

**Comment by redox** [comment]
@PeterDaveHello good catch; was a tricky one :/

**Comment by vigneshshanmugam** [comment]
Isn't because of the double binding in the events?. 

Ideally, we need to unbind before binding the change and keyup events. 

Clicking on anchor links triggers the searchHandler() which shouldn't.

**Comment by PeterDaveHello** [comment]
Thank you guys :+1:
