### ISSUE TITLE
Copy button should disappear after mouse move out

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#41]
as title

**Comment by mkautzmann** [comment]
Hi @PeterDaveHello.

What browser are you testing with?

It appears to be working recently.

I've tested in Chrome and Safari and it looks OK.

**Comment by PeterDaveHello** [comment]
hmmm ... I tested on latest chrome/firefox, I think we are not talking about the same thing, sorry for the ambiguous title, I meant if the mouse is not on any result, there should not be a copy button, but currently, it'll be a copy button on the last item I hovered on, not sure if you don't have this problem? Thanks!

**Comment by mkautzmann** [comment]
Ohh, now I get it. Yes, it's happening.

OK, I'll take a look.

**Comment by PeterDaveHello** [comment]
@mkautzmann :Thank you
