### ISSUE TITLE
Hold old, indexed data when failed on grabing libs info

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#46]
Warning added in https://github.com/cdnjs/new-website/commit/242c632a40452364f051f2eda231e4b7732e789e, and randomly got warning on some libs.

I think the quality of the network/internet here is fine, not sure what's the reason why, should mark it as an issue.

**Comment by redox** [comment]
Oh interesting, maybe it's a rate-limit issue; I know GitHub is pretty restrictive on that :/

**Comment by PeterDaveHello** [comment]
Yeah, I wonder if should sleep for a short time, or even use two client with different key, haha.
Don't want to make the reindex process slower at all.

**Comment by PeterDaveHello** [comment]
hmmmm ... if it's rate-limit issue, I think upstream npm package `github` should handle it, maybe retry depends on the error code.

**Comment by IonicaBizau** [comment]
@PeterDaveHello @redox I guess you're not trying to make more than 5000 requests / hour. :smile: Or do you?

**Comment by redox** [comment]
Last time I checked we were doing ~1K requests per indexing process. If you try to reindex 5 times in an hour, it could become an issue :)

**Comment by PeterDaveHello** [comment]
hmmmm ... about 1.25K request per reindex
all the error messages are just 404 not found ... hmmm ...

**Comment by PeterDaveHello** [comment]
@redox, is it possible to use old data(partial) when grabbing failed?

**Comment by redox** [comment]
Oh ok, that make sense then -> their associated package.json probably refers to outdated repositories. What do you mean exactly by "old data(partial)"? Like getting the previous count if it was successfully indexed before?

**Comment by PeterDaveHello** [comment]
Yeah, the indexed data from last time.

Most libs' link been fixed in this commit:
https://github.com/cdnjs/cdnjs/commit/43c20c2389fb50c7b1d2c62788e5c84b8fa6e2e1

Related issue:
https://github.com/cdnjs/cdnjs/issues/4695

Btw, got the same problem on another api token, and I don't think I reached 5k reqs/hour.

**Comment by PeterDaveHello** [comment]
BTW, the real missing repo libs:
```
Got a problem on andyet/ICanHaz.js !!!
Got a problem on projectBS/bsJS !!!
Got a problem on neteye/jquery-plugins !!!
Got a problem on wjosdejong/jsoneditoronline !!!
Got a problem on tybenz/legojs !!!
Got a problem on j-l-n/noti.js !!!
Got a problem on n33/skel-layers !!!
```

**Comment by redox** [comment]
Yeah, could work if we use a `partialUpdateObject` operation instead of the `addObject` one in case we don't get any GH answer: it will avoid overriding the original attribute values.

So you mean only those 7 repos are returning a 404?

**Comment by PeterDaveHello** [comment]
Yeah, their authors dropped them :sob: 
Anyway, exception handling and rollback mechanism should be good.

**Comment by PeterDaveHello** [comment]
Temporarily workaround ... 

Same grabbed info to GitHub.repos.meta.json, and then reuse it

* fd85194 add GitHub.repos.meta.json
* c3f92a1 save repo meta data for index

Though we don't really need real time data, just let another program to update the GitHub.repos.meta.json.
