### ISSUE TITLE
algoliasearch reindex failed

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#51]
Exit without error status but only end with `** Enrich xxxxx/yyyy`, tried 2 times, seems it didn't push and commit the result.

**Comment by redox** [comment]
Hmmm, let me try that.

**Comment by redox** [comment]
It's working from here: I've just reindexed everything. Any chance your GitHub token used to enrich the libraries has been revoked?

**Comment by PeterDaveHello** [comment]
Hi @redox, thanks for your fast reply, in fact, I was trying to do the same thing as you - reindex on another server, and it works very well, so I'm going to check what's wrong on the main building server, let's leave issue opened until I fix it, thanks for your help again :+1:

**Comment by PeterDaveHello** [comment]
BTW, same GitHub token :smile:

**Comment by PeterDaveHello** [comment]
It works now ... though I didn't change things, maybe it's my server's problem.

**Comment by redox** [comment]
:+1: Good news then, I like those issues resolving alone :)
