### ISSUE TITLE
Do not show the whole file lists in lib page

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#54]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=25535618)](https://www.bountysource.com/issues/25535618-do-not-show-the-whole-file-lists-in-lib-page?utm_source=25535618&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Some libs have too many files and the end users may not need to access them directly, should not display all of them by default, maybe hide fonts and images by default will be good, we can also hide the js/css files without minify by default, and add a button for showing the whole file list.

**Comment by bhargav175** [comment]
@PeterDaveHello Which libs are those? Can you share links to the pages of those libs in the website?

**Comment by PeterDaveHello** [comment]
 @bhargav175 sorry for the late reply, I think you can take a look at `material-design-icons`, it's version 3.0.1 contains 82290 files.

**Comment by qas612820704** [comment]
@PeterDaveHello Hi!

Can you talk about this more concretely?

What file should be remain in `material-design-icons` example?

**Comment by PeterDaveHello** [comment]
Hi @qas612820704, in the case of `material-design-icons`, there are 82290 files, most of them are `png`, `svg`, etc, the resources that most users won't directly use(map file would also be not), I prefer to display the file mentioned by the `filename` property in `package.json`, the others, also display `*.min.js` & `*.min.css` as default.
