### ISSUE TITLE
Current search doesn't match keywords on the repository's and owner's name.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#55]
I think we can add it into the index!

**Comment by redox** [comment]
sure thing, let me submit a PR for that

**Comment by PeterDaveHello** [comment]
Thanks @redox, I just assigned you this one!

**Comment by redox** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Thanks @redox, I;m going to rebuild it now!
