### ISSUE TITLE
add star and fork  on each lib's page

### ISSUE THREAD

**Issue by maruilian11** [cdnjs/new-website#60]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=25713763)](https://www.bountysource.com/issues/25713763-add-star-and-fork-on-each-lib-s-page?utm_source=25713763&utm_medium=shield&utm_campaign=ISSUE_BADGE)

maybe we can also add star count and fork count on each lib's page, not just on the search page.
for example on [angular.js](https://cdnjs.com/libraries/angular.js)

**Comment by IonicaBizau** [comment]
@PeterDaveHello How do we fetch fork and star counts? Maybe we could use [`gh.js`](https://github.com/IonicaBizau/gh.js). :smile: :four_leaf_clover:

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/new-website/blob/master/reindex.js#L104-L127

I wonder we can write this info to packages.min.json

**Comment by IonicaBizau** [comment]
> I wonder we can write this info to packages.min.json

And how do you update when counts are changing?

**Comment by redox** [comment]
> I wonder we can write this info to packages.min.json

That would be cool :)

> And how do you update when counts are changing?

Updating the counts once a day is probably enough, so cron + code that does something like in `reindex.js` ?

**Comment by PeterDaveHello** [comment]
Grab it in every build:
https://github.com/cdnjs/cdnjs/blob/master/build/packages.json.js

**Comment by IonicaBizau** [comment]
What if we would use it on the client side? That means the user's ip has a limited requests/hour, but still enough I guess.

**Comment by PeterDaveHello** [comment]
It will be much slower, make GitHub's server loading heaver, and I don't think we realtime data.

**Comment by redox** [comment]
> What if we would use it on the client side?

Not sure I see the advantage of querying the GH API from the client side, the counts don't need to be exact/realtime so I think it would be cleaner & faster to store them in the backend, no?

**Comment by IonicaBizau** [comment]
Yep, then in `packages.min.json`. :smile:

**Comment by redox** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Hey guys, would you mind that we leave this issue for our @cdnjs/intern team to take is as a practice? I wanna make them working on code level issues also.

**Comment by IonicaBizau** [comment]
Using `gh.js` we can get the stars count using:

```js
var GitHub = require("gh.js");

var gh = new GitHub({
    token: "an optional token"
});

gh.get("repos/<username>/<repository>", function (err, repo) {
    console.log(err || repo.stargazers_count);
});
```

:smile:

**Comment by redox** [comment]
:+1: @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Ping @cdnjs/intern

**Comment by Piicksarn** [comment]
i got it!
Fighting!:punch:

**Comment by maruilian11** [comment]
got it.

**Comment by PeterDaveHello** [comment]
Added a $5 minimum bounty for this issue.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern @cdnjs/intern2 any one want to take this?

**Comment by pvnr0082t** [comment]
I'd like to try it.

**Comment by maruilian11** [comment]
I can try it in my free time, too.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please claim your bounty here: https://www.bountysource.com/issues/25713763-add-star-and-fork-on-each-lib-s-page
