### ISSUE TITLE
Make 'Go back' button bring the page back to search result

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#62]
When user search a lib and click a result, the browser brings user to the lib's page, but when click go back button, it'll go to the main page of website, should bring the user back the search result instead of the main page of website.

I guess one solution is to change the url in realtime when user stop typing, and also add a record in browser's history.

**Comment by redox** [comment]
Yes we could `pushState` with the query (playing with `setTimeout` and `clearTimeout` to not change the URL at each keystroke). You want your @cdnjs/intern team to work on that as well?

**Comment by PeterDaveHello** [comment]
@redox I think they should finish previous issue(#60) first, you're very welcome to take this issue :smile:

**Comment by PeterDaveHello** [comment]
Since modern browsers seem to remember the input when we go back, I'll do a simple trick to trigger the searchHandler again here, @redox if you are still interested in help or give suggestions, I'll be really appreciate! Thanks.
