### ISSUE TITLE
It's easy to got "connect ETIMEDOUT" error while reindexing.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#67]
Just found this problem and open a ticket as a record.

**Comment by redox** [comment]
Hmmm, any chance you have a backtrace @PeterDaveHello? I can start upgrading the AlgoliaSearch API client, will help.

**Comment by PeterDaveHello** [comment]
hmmmm ... the timeout is between my machine and GitHub, I'm finding the problem, not sure if is because the network quality.

**Comment by PeterDaveHello** [comment]
I wonder if the speed to create connection is too fast so been blocked by my ISP :sob: 
Will find a method to fix it ...

**Comment by PeterDaveHello** [comment]
I wanna set a longer timeout, hmmmm ... but if it was been blocked ... this may not help

**Comment by PeterDaveHello** [comment]
not code level issue and don't have it now.
