### ISSUE TITLE
Undefined stars and other similar info in search result.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#69]
Like riot.
![default](https://cloud.githubusercontent.com/assets/3691490/9705969/4f609c0a-5509-11e5-8039-4baa7ed8efd8.png)

**Comment by PeterDaveHello** [comment]
The reason maybe the moved repo:
https://github.com/muut/riotjs -> https://github.com/riot/riot

**Comment by PeterDaveHello** [comment]
Adding detection when reindexing.

**Comment by redox** [comment]
> The reason maybe the moved repo:
> https://github.com/muut/riotjs -> https://github.com/riot/riot

Yes, for sure that's the root cause.

> Adding detection when reindexing.

Thanks for taking care of it @PeterDaveHello !

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Added a little bit more info, but should better collect the errors and print the all errors again before exit.

Wondering should exit without 0, but some repos were deleted, should consider to remove repo info in package.json or something else.

**Comment by PeterDaveHello** [comment]
Repo urls fixed in as workaround.
https://github.com/cdnjs/cdnjs/commit/82aab453b911dbae18d3ddb451edb86f1312a3d1

**Comment by PeterDaveHello** [comment]
![default](https://cloud.githubusercontent.com/assets/3691490/9706349/e7c9bdf4-5514-11e5-9aa7-0e16e5d943b9.png)

**Comment by IonicaBizau** [comment]
I think we should use [this feature](https://developer.github.com/changes/2015-05-26-repository-redirects-are-coming/).

**Comment by PeterDaveHello** [comment]
https://github.com/mikedeboer/node-github/issues/257
