### ISSUE TITLE
Add links to privacy policy and t&c text

### ISSUE THREAD

**Issue by petecooper** [cdnjs/new-website#7]
Had a couple of mentions about privacy policy in the last few days, best to address this soon.

https://github.com/cdnjs/cdnjs/issues/3439
https://news.ycombinator.com/item?id=7931027

**Comment by PeterDaveHello** [comment]
cc @ryankirkman @thomasdavis @drewfreyling @IonicaBizau

**Comment by plaa** [comment]
Any updates on this? For corporate users this would be very important.

**Comment by MattIPv4** [comment]
@ryankirkman @thomasdavis Anything regarding this, would it just be best to link to the Cf ones per what pete suggested in https://github.com/cdnjs/cdnjs/issues/3439 ?

**Comment by MattIPv4** [comment]
After checking in with folks at Cf, we're simply going to link to the Cf docs for now.

**Comment by xtuc** [comment]
https://github.com/cdnjs/cdnjs/issues/13272 has been closed, closing this
