### ISSUE TITLE
Add GitHub repo link in library's page

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#70]
Link to its GitHub or other source code hosting platform.
Should be care of ssh and git protocol in [packages.min.json](public/packages.min.json), should use https instead(but in web server only).

**Comment by IonicaBizau** [comment]
We could use [`git-url-parse`](https://github.com/IonicaBizau/node-git-url-parse)–it will look something like this:

```js
GitUrlParse("my-ssh-url").toString("https");
```

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Start to work on it with in an hour.

**Comment by IonicaBizau** [comment]
:tada:
