### ISSUE TITLE
Search index didn't been updated but reindex had no error.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#73]
Hi @redox, seems our search index didn't been update, I didn't see any error and also tried to re-index again with some updates but got same result.
I've pushed the latest build on [meta branch](https://github.com/cdnjs/new-website/tree/meta), would you please take a look at it when you have time? Thanks a lot!

**Comment by redox** [comment]
Hi @PeterDaveHello, I just tried to run the reindex script (from the meta branch) and all went well. Do you have any error?

Here are my logs:

```
[...]
** Enrich smcllns/css-social-buttons, 1476 star(s) ...
** Enrich jaukia/zoomooz, 1344 star(s) ...
** Enrich dropbox/zxcvbn, 2461 star(s) ...
** Enrich zurb/ink, 4806 star(s) ...
* Initializing the index
* Indexing 1440 libraries
* Moving index to production
```

And the index is up-to-date.

**Comment by PeterDaveHello** [comment]
No, I didn't get any error, I check it twice, but now I can see the updated result, strange, I found this problem because I can not see the result after 2 hours after I reindexed. Maybe it was cache or something? I remember it's fast before.

**Comment by redox** [comment]
OK, so for cdnjs.com we've enabled the [world-wide replication](https://www.algolia.com/dsn) so maybe you were targeting a slave replicate (we route the query to the closest datacenter) that was a bit laggy (replication is done asynchronously).

**Comment by PeterDaveHello** [comment]
Oh, cool, so what's the reasonable laggy here? I meant if I found the index didn't been updated, how long should I wait until opening a issue ticket? Thanks!

**Comment by redox** [comment]
We're generally speaking about a few seconds, then in case of major network issues across continents -> it can take up to several minutes or hours (but I'm not aware of any issues this morning). Where are you located right now @PeterDaveHello ?

**Comment by PeterDaveHello** [comment]
Taiwan, Asia.

**Comment by redox** [comment]
OK we're used to see a high latency between US-East and South-East Asia but nothing special today. Could you let us know when that happens again so we can check if the replication job is stuck/delayed or so? In the meantime, I think we can close the issue.

**Comment by PeterDaveHello** [comment]
Okay, no problem.
