### ISSUE TITLE
Fuzzy search on api

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#74]
angular.js:
http://api.cdnjs.com/libraries?search=angular.js

angularjs
http://api.cdnjs.com/libraries?search=angularjs

cannot see angular.js by searching angularjs

**Comment by PeterDaveHello** [comment]
hmmmm ... but i wonder if we can or we should just migrate with algolia's search

**Comment by redox** [comment]
I would definitely proxify the Algolia API for the search endpoint, the [Hacker News Search](https://hn.algolia.com/api) is also doing it.

**Comment by PeterDaveHello** [comment]
oh cool, can you take this work @redox ?

**Comment by redox** [comment]
Sure thing!

**Comment by redox** [comment]
@PeterDaveHello done!

**Comment by PeterDaveHello** [comment]
Oh cool, let's see what we'll get!

**Comment by PeterDaveHello** [comment]
It break `assets`, see cdnjs/cdnjs#5688
