### ISSUE TITLE
Human readable api query output

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#75]
saerch angularjs:

http://api.cdnjs.com/libraries?search=angularjs
```js
{"results":[{"name":"angularjs-nvd3-directives","latest":"https://cdnjs.cloudflare.com/ajax/libs/angularjs-nvd3-directives/0.0.7/angularjs-nvd3-directives.min.js"},{"name":"angularjs-toaster","latest":"https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.15/toaster.min.js"}],"total":2}
```

Is hard to read for human, I hope we can have something like
http://api.cdnjs.com/libraries?search=angularjs&output=human
```js
{
  "total": 2,
  "results": [
    {
      "latest": "https://cdnjs.cloudflare.com/ajax/libs/angularjs-nvd3-directives/0.0.7/angularjs-nvd3-directives.min.js",
      "name": "angularjs-nvd3-directives"
    },
    {
      "latest": "https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.15/toaster.min.js",
      "name": "angularjs-toaster"
    }
  ]
}
```

So it'll be easier to read for us!

**Comment by PeterDaveHello** [comment]
Got strange problem here, deployed api (on heroku) keep sending human readable results, but I have no problem locally, not sure if the cdn did something. @ryankirkman would you please help me test it? Thanks.

**Comment by PeterDaveHello** [comment]
@terinjokes do you have any idea? I guess maybe cloudflare will do something on it?

**Comment by thomasdavis** [comment]
Ahh I really think it's on the clients behalf to pretty print, we could add the method in as a convenience factor. But we should always try to keep things minimal and quick at cdnjs so I'd have to vote no to adding that feature.

If you want a great client for testing API's, check out Postman, they also have a pretty print option built in.

**Comment by terinjokes** [comment]
Or [jq](https://stedolan.github.io/jq/)

**Comment by PeterDaveHello** [comment]
@thomasdavis, the pretty version only shows when query `?output=human`

**Comment by PeterDaveHello** [comment]
it works great locally, I just don't know why it doesn't show the result properly after deployed.

**Comment by thomasdavis** [comment]
So cloudflare minifies the whole domain, if we have some spare page rules I can set it up to deactivate when it detects the query string.

**Comment by PeterDaveHello** [comment]
but it's doing the reverse thing in this case?

**Comment by thomasdavis** [comment]
I'm confused now,  the query string pretty prints it but you are saying in
production it is still minified regardless?

On Mon, Sep 28, 2015 at 10:02 AM, Peter Dave Hello <notifications@github.com
> wrote:

> but it's doing the reverse thing in this case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/new-website/issues/75#issuecomment-143605801>.
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by PeterDaveHello** [comment]
@thomasdavis I meant is should be minifiedbby our app but it did not, and i did not query with `?output=human`

**Comment by PeterDaveHello** [comment]
@thomasdavis It is simple: with `?output=human`, okay, print with pretty, otherwise, should be minied, and the behavior is correct locally

**Comment by PeterDaveHello** [comment]
Though we use standard mode on cloudflare.com cdn, I thought it doesn't work properly, I will try to remove the query and transfer it to kind of route, and see what we got.

**Comment by PeterDaveHello** [comment]
Should be good now.
