### ISSUE TITLE
add api page

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#76]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=26648068)](https://www.bountysource.com/issues/26648068-add-api-page?utm_source=26648068&utm_medium=shield&utm_campaign=ISSUE_BADGE)

To tell people how to use our api, ref:
https://github.com/cdnjs/cdnjs#api

**Comment by PeterDaveHello** [comment]
We can construct this page http://api.cdnjs.com/

**Comment by willyb321** [comment]
I've started working on this [here](https://github.com/willyb321/new-website).

**Comment by PeterDaveHello** [comment]
@willyb321 I think it's time to claim your bounty on the page 👍

**Comment by willyb321** [comment]
@PeterDaveHello done!

**Comment by PeterDaveHello** [comment]
Confirmed!
