### ISSUE TITLE
api server seems to be very unstable

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#82]
Should figure it out ... cc @cdnjs/owners 

![default](https://cloud.githubusercontent.com/assets/3691490/9899678/084fae28-5c8e-11e5-8b34-d28e3d31031e.png)
![default](https://cloud.githubusercontent.com/assets/3691490/9899686/1cfebd8c-5c8e-11e5-8dea-b7472d2b3e52.png)

**Comment by redox** [comment]
Any logs?

**Comment by thomasdavis** [comment]
I wonder if we updated the dynos to be the new paid versions. @ryankirkman

On Wed, Sep 16, 2015 at 6:16 PM, Sylvain Utard <notifications@github.com>
wrote:

> Any logs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/new-website/issues/82#issuecomment-140665983>.
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by ryankirkman** [comment]
Ohhhhh, I see. Let me check

**Comment by ryankirkman** [comment]
Yeah, this has only been happening recently (as per New Relic). I switched the Heroku dyno over from being a traditional dyno to being a Hobby dyno, so we'll see if that helps.

/cc @thomasdavis

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by ryankirkman** [comment]
@redox Here are some recent logs: https://drive.google.com/folderview?id=0B1atQwQSG7RRUzhSVl9fdTl5NEU&usp=sharing

**Comment by PeterDaveHello** [comment]
hmmmm ... no problem now.
