### ISSUE TITLE
Request: display file size

### ISSUE THREAD

**Issue by kevinSuttle** [cdnjs/new-website#83]
It would be great to have the file size and possible perf. statistics listed on a library page. 
Lots of space on that right side to add some more valuable info.

**Comment by PeterDaveHello** [comment]
Duplicated with https://github.com/cdnjs/cdnjs/issues/4187

**Comment by PeterDaveHello** [comment]
@kevinSuttle please move to cdnjs/cdnjs#4187 and give your +1 if you want this feature back, thanks.
