### ISSUE TITLE
Should have "Copy Script/Link Tag" option in copy button in library page

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/new-website#84]
We only have it in search result now.

**Comment by PeterDaveHello** [comment]
hmmm ... too busy to work on this, @cdnjs/team-cdnjs @cdnjs/intern please help me fix this issue, anyone will be welcome thanks!

**Comment by ryankirkman** [comment]
**Problem:**
![image](https://cloud.githubusercontent.com/assets/54405/10301305/e021e93e-6bb5-11e5-8eac-8a019adab40a.png)

**What it should look like:**
![image](https://cloud.githubusercontent.com/assets/54405/10301309/f9d0080c-6bb5-11e5-976e-4ab7d58e66d0.png)

**Comment by terinjokes** [comment]
The script tag should include `crossorigin="anonymous"`, as per [Mozilla](https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/)

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by mkautzmann** [comment]
It looks like it's working now, at least in my tests, can you confirm?

It's not passing the `crossorigin="anonymous"` attribute though, I can take a look into that.

**Comment by PeterDaveHello** [comment]
@mkautzmann we meant on the libraries' page, not the search result, like jquery - https://cdnjs.com/libraries/jquery, do you have the same feature?

**Comment by mkautzmann** [comment]
Sorry, I was checking both the search page and the browse libraries page not inside any specific library.

I now understand the behavior. I'll look into it.

**Comment by PeterDaveHello** [comment]
@mkautzmann Thanks!

**Comment by Shadowmad** [comment]
Please close the issue as I can see it has been fixed. Actually mislead me for a little while. Thanks!

**Comment by PeterDaveHello** [comment]
Nope, @Shadowmad you must misunderstand it.

**Comment by Shadowmad** [comment]
@PeterDaveHello  Sorry, I missed the idea, now I got it. What has been fixed is copy script tag on search page, but not in a libriary. I will look into that. Sorry again. Thanks

**Comment by PeterDaveHello** [comment]
@Shadowmad no problem.
