### ISSUE TITLE
Firefox complains about SHA-1

### ISSUE THREAD

**Issue by szepeviktor** [cdnjs/new-website#85]
> This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.
*Firefox 42*

Good morning!

Please consider using SHA-256 signed certificates.
Thank you!

**Comment by PeterDaveHello** [comment]
@szepeviktor Cc @cdnjs/team-cdnjs

**Comment by szepeviktor** [comment]
Thank you @PeterDaveHello.

**Comment by prdonahue** [comment]
CloudFlare TLS PM here. @terinjokes brought this to my attention.

We're in the process of issuing SHA-256 certificates for all of the several million zones on us (incl. cdnjs.com), and once done, this warning will disappear. We expect this to happen within the next few days.

**Comment by PeterDaveHello** [comment]
@prdonahue Thanks

**Comment by szepeviktor** [comment]
Thank you.
I'm closing this because the *next few days* is close enough.

**Comment by szepeviktor** [comment]
Excuse me for reporting this in the wrong place.
https://github.com/cdnjs/cdnjs/issues/4807

**Comment by prdonahue** [comment]
Just wanted to let you know that cdnjs.com now has three (3) certificates per our new standard fall back. Modern user agents will get a SHA-256 ECDSA cert or a SHA-256 RSA (if it doesn't have ECC support) while legacy UAs will get SHA-1 RSA.

```
$ echo | openssl s_client -connect cdnjs.com:443 -tls1_2 -sigalgs ECDSA+SHA256:RSA+SHA256:RSA+SHA1 2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm" | tail -1
    Signature Algorithm: ecdsa-with-SHA256
```

```
$ echo | openssl s_client -connect cdnjs.com:443 -tls1_2 -sigalgs RSA+SHA256:RSA+SHA1 2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm" | tail -1
    Signature Algorithm: sha256WithRSAEncryption
```

```
$ echo | openssl s_client -connect cdnjs.com:443 -tls1_1  2>/dev/null | openssl x509 -noout -text | grep "Signature Algorithm" | tail -1
    Signature Algorithm: sha1WithRSAEncryption
```

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
https://dev.ssllabs.com/ssltest/analyze.html?d=cdnjs.com&s=104.24.29.58&hideResults=on&latest
