### ISSUE TITLE
Consider switching from Flash to JS for "Copy to clipboard"

### ISSUE THREAD

**Issue by zenorocha** [cdnjs/new-website#94]
I noticed you guys still use Flash for that "Copy to Clipboard" button. What do you think of switching to [clipboard.js](http://clipboardjs.com/)?

**Comment by PeterDaveHello** [comment]
@zenorocha It will be great, we can also refactor some of our code at the mean time.

**Comment by IonicaBizau** [comment]
@zenorocha :joy: :+1: Kill flash, yeah! :boom:

**Comment by mkautzmann** [comment]
:+1: Totally agree, I can work on the change. @PeterDaveHello Is it OK to send a PR later?

**Comment by PeterDaveHello** [comment]
@mkautzmann of course, feel free to do that!

**Comment by mkautzmann** [comment]
Just sent a PR

**Comment by PeterDaveHello** [comment]
Okay, I am going to review it!

**Comment by PeterDaveHello** [comment]
Changed in #97
